apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-jenkins
  namespace: cp-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp-jenkins
  template:
    metadata:
      labels:
        app: cp-jenkins
    spec:
      containers:
      - name: jenkins
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        env:
        - name: JENKINS_ADMIN_ID
          value: {{ .Values.adminUser | quote }}
        - name: JENKINS_ADMIN_PASSWORD
          value: {{ .Values.adminPassword | quote }}
        - name: JENKINS_OPTS
          value: "--prefix=/jenkins"
        - name: JAVA_OPTS
          value: >
            -Djenkins.install.runSetupWizard=false
            -Djenkins.model.Jenkins.rootUrl=http://a09dfe47f3ea541ac82425ea9bf69fe4-1565111427.us-east-1.elb.amazonaws.com/jenkins
            -Dhudson.footerURL=http://a09dfe47f3ea541ac82425ea9bf69fe4-1565111427.us-east-1.elb.amazonaws.com/jenkins