apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cp-jenkins
  namespace: cp-jenkins
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Prefix /jenkins;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Port $server_port;
    nginx.ingress.kubernetes.io/proxy-redirect-from: ~^http://[^/]+(/jenkins)?(.*)$
    nginx.ingress.kubernetes.io/proxy-redirect-to: '$2'
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /jenkins
        pathType: Prefix
        backend:
          service:
            name: cp-jenkins
            port:
              number: 8080