apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cp-jenkins
  namespace: cp-jenkins
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /jenkins
        pathType: Exact
        backend:
          service:
            name: cp-jenkins
            port:
              number: 8080