apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cp-jenkins-pvc
  namespace: cp-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
