apiVersion: v1
kind: Service
metadata:
  name: cp-jenkins
  namespace: cp-jenkins
  labels:
    app: cp-jenkins
spec:
  type: NodePort
  selector:
    app: cp-jenkins
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    