apiVersion: v1
kind: Service
metadata:
  name: cp-jenkins
  labels:
    app: cp-jenkins
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: cp-jenkins
