apiVersion: v1
kind: Service
metadata:
  name: cp-jenkins
  namespace: cp-jenkins
  labels:
    app: cp-jenkins
spec:
  type: ClusterIP
  selector:
    app: cp-jenkins
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP