apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}
  labels:
    {{include "jenkins.labels" . }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: {{ .Values.service.nodePort | default 30080 }}
  selector:
    app.kubernetes.io/name: {{ include "jenkins.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
