replicaCount: 1

image:
  repository: jenkins/jenkins
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  storageClass: gp2

adminUser: admin
adminPassword: admin123
