replicaCount: 1

image:
  repository: jenkins/jenkins
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080 # Specify a custom NodePort or leave it blank for Kubernetes to assign one

# persistence:
#   enabled: true
#   accessMode: ReadWriteOnce
#   size: 8Gi
#   storageClass: gp2

adminUser: admin
adminPassword: admin123
